//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneAPI.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DroneAPI.Models.ModelTexts", typeof(ModelTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drone not found..
        /// </summary>
        public static string Message_DroneNotFound {
            get {
                return ResourceManager.GetString("Message_DroneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected drone does not suitable for caring out the provided load..
        /// </summary>
        public static string Message_DroneNotSuitableForCaringTheLoad {
            get {
                return ResourceManager.GetString("Message_DroneNotSuitableForCaringTheLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DroneState:{0}, DroneWeightLimit:{1}, BatteryCapacity:{2}..
        /// </summary>
        public static string Message_DroneProperties {
            get {
                return ResourceManager.GetString("Message_DroneProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medications not found..
        /// </summary>
        public static string Message_MedicationsNotFound {
            get {
                return ResourceManager.GetString("Message_MedicationsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid drone model..
        /// </summary>
        public static string Validation_DroneModel {
            get {
                return ResourceManager.GetString("Validation_DroneModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length {0} exceeded..
        /// </summary>
        public static string Validation_MaxLengthExceeded {
            get {
                return ResourceManager.GetString("Validation_MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max value {0} exceeded..
        /// </summary>
        public static string Validation_MaxValueExceeded {
            get {
                return ResourceManager.GetString("Validation_MaxValueExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
